apiVersion: v1
kind: Service
metadata:
  name: redis-single
  namespace: redis
  labels:
    app: redis-single
spec:
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
  selector:
    app: redis-single
