apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-single
  namespace: redis
spec:
  serviceName: "redis-single"
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-single
      namespace: redis
    spec:
      containers:
      - name: redis-single
        image: redisaas/docker-redis:3.0.7.2
        imagePullPolicy: IfNotPresent
        env:
          - name: REDIS_PASSWORD
            value: moria 
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
        volumeMounts:
          - name: "redis-data"
            mountPath: "/var/lib/redis"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      annotations:
          volume.beta.kubernetes.io/storage-class: "nfs"
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 200M
