apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: eureka
  name: eureka
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
     containers:
     - image: calvindai/macula-cloud-eureka:1.0
       imagePullPolicy: Always
       name: eureka
       ports:
       - containerPort: 8761
         name: eureka
         protocol: TCP
       
