apiVersion: v1
kind: Service
metadata:
    name: mysql-master-service-1
spec:
  selector:
      app: mysql-master-service-1
  ports:
  - port: 3306
    name: mysql 

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: mysql-master-1
  name: mysql-master-1
spec:
  serviceName: mysql-master-service
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mysql-master-1
  template:
    metadata:
      labels:
        app: mysql-master-1
    spec:
      containers:
      - env:
        - name: AUTO_INCREMENT_INCREMENT
          value: "2"
        - name: AUTO_INCREMENT_OFFSET
          value: "1"
        - name: REPLICATIONTYPE
          value: "mastertomaster"
        - name: MYSQL_MASTER_SERVICE_HOST
          value: "mysql-master-service-2"
        - name: MYSQL_REPLICATION_PORT
          value: "3306"
        - name: MYSQL_REPLICATION_USER
          value: "repl"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "repl"
        image: calvindai/mysql-cluster:1.0
        imagePullPolicy: IfNotPresent
        name: mysql
        volumeMounts:
        - name: mysql-master-data
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  volumeClaimTemplates:
  - metadata:
       name: mysql-master-data
       annotations:
          volume.beta.kubernetes.io/storage-class: "nfs"
    spec:
       accessModes:
       - ReadWriteOnce
       resources:
          requests:
            storage: 3Gi 
