apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: mysql-slave
  name: mysql-slave
spec:
  serviceName: mysql-slave-service
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
        version: v1
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MYSQL_MASTER_SERVICE_HOST
          value: "mysql-master-service"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "repl"
        - name: MYSQL_REPLICATION_USER
          value: "repl"
        - name: MYSQL_REPLICATION_PORT
          value: "3306"
        image: calvindai/mysql-slave:1.0
        imagePullPolicy: Always
        name: mysql
        volumeMounts:
        - name: mysql-slave-data
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  volumeClaimTemplates:
  - metadata:
       name: mysql-slave-data
       annotations:
          volume.beta.kubernetes.io/storage-class: "nfs"
    spec:
       accessModes:
       - ReadWriteOnce
       resources:
          requests:
            storage: 3Gi 
