apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: redis
  labels:
    app: redis-master
spec:
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
  selector:
    app: redis
    node: master
    appCluster: redis-cluster
