apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport-service
spec:
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379
    type: NodePort
  selector:
    app: redis
    appCluster: redis-cluster  
